@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Mon Oct 28 21:20:11 +0100 2019
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto 832fba6f2cef4fb0abae07c99a222d6d --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot tb_mult8_behav xil_defaultlib.tb_mult8 -log elaborate.log"
call xelab  -wto 832fba6f2cef4fb0abae07c99a222d6d --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot tb_mult8_behav xil_defaultlib.tb_mult8 -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
